{"name": "test_get_customer_details_by_customer_id", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'Schemas/get_customer_details_by_customer_id.json'", "trace": "@pytest.mark.smoke\n    def test_get_customer_details_by_customer_id():\n        Customer_id = 12767\n    \n        response = get_user_details_by_customer_id.get_user_details(Customer_id = Customer_id)\n        print(\"Response Status \",response.status_code)\n        print(\"Response Body:\", response.text)\n    \n        assert response.status_code == 200, f\"Expected 200, got {response.status_code}\"\n        response_json = response.json()\n>       with open(\"Schemas/get_customer_details_by_customer_id.json\") as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'Schemas/get_customer_details_by_customer_id.json'\n\nTests\\API_Testing\\GET_TESTING\\test_get_customer_details_by_customer_id.py:18: FileNotFoundError"}, "attachments": [{"name": "stdout", "source": "2a578130-0877-47cc-96a0-81ef73ac625f-attachment.txt", "type": "text/plain"}], "start": 1761061270181, "stop": 1761061278365, "uuid": "cd957dbd-a477-4abe-b832-d563c1ea6110", "historyId": "73719dbce4d1c2818a886e927d394555", "testCaseId": "73719dbce4d1c2818a886e927d394555", "fullName": "Tests.API_Testing.GET_TESTING.test_get_customer_details_by_customer_id#test_get_customer_details_by_customer_id", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "Tests.API_Testing.GET_TESTING"}, {"name": "suite", "value": "test_get_customer_details_by_customer_id"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "15812-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.API_Testing.GET_TESTING.test_get_customer_details_by_customer_id"}], "titlePath": ["Tests", "API_Testing", "GET_TESTING", "test_get_customer_details_by_customer_id.py"]}